Changing ssm dns configuration to support more generic approach

diff --git a/scripts/post-install/nat b/scripts/post-install/nat
--- a/scripts/post-install/nat
+++ b/scripts/post-install/nat
@@ -53,9 +53,25 @@ fi
 
 # ensure this zone is in deploymentsystem hosted zone, also get hostedzoneid from ssm parameter store
 localdomain="$( hostname -d )"
-hostedzoneid="$( aws ssm get-parameter --name /${ENVIRONMENT}/DeploymentSystem/Dns/Domains/${localdomain}/HostedZoneId --query "Parameter.Value" --output text )"
+hostedzonename="$( aws ssm get-parameter --name /Config/Dns/HostedZoneName --query "Parameter.Value" --output text )"
+if [ "${hostedzonename}x" == "x" ];then
+  echo "Failed to find ssm parameter for HostedZoneId from (/Config/Dns/HostedZoneName)"
+  exit 1
+fi
+if [ "${hostedzonename}" != "${localdomain}" ];then
+  echo "Local domain name (${localdomain}) does not match hosted zone name (${hostedzonename}) - refusing to update dns"
+  exit 1
+fi
+
+hostedzoneid="$( aws ssm get-parameter --name /Config/Dns/HostedZoneId --query "Parameter.Value" --output text )"
 if [ "${hostedzoneid}x" == "x" ];then
-  echo "Failed to find ssm parameter for HostedZoneId from (/${ENVIRONMENT}/DeploymentSystem/Dns/Domains/${localdomain}/HostedZoneId)"
+  echo "Failed to find ssm parameter for HostedZoneId from (/Config/Dns/HostedZoneId)"
+  exit 1
+fi
+
+hostedzoneid="$( aws ssm get-parameter --name /Config/Dns/HostedZoneId --query "Parameter.Value" --output text )"
+if [ "${hostedzoneid}x" == "x" ];then
+  echo "Failed to find ssm parameter for HostedZoneId from (/Config/Dns/HostedZoneId)"
   exit 1
 fi
 
